# Generated by Django 4.2.9 on 2024-02-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Change_Type", models.CharField(max_length=255)),
                ("Covered_Recipient_Type", models.CharField(max_length=255)),
                (
                    "Teaching_Hospital_CCN",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Teaching_Hospital_ID",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Teaching_Hospital_Name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Covered_Recipient_Profile_ID", models.CharField(max_length=255)),
                ("Covered_Recipient_NPI", models.CharField(max_length=255)),
                ("Covered_Recipient_First_Name", models.CharField(max_length=255)),
                (
                    "Covered_Recipient_Middle_Name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Covered_Recipient_Last_Name", models.CharField(max_length=255)),
                (
                    "Covered_Recipient_Name_Suffix",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Recipient_Primary_Business_Street_Address_Line1",
                    models.CharField(max_length=255),
                ),
                (
                    "Recipient_Primary_Business_Street_Address_Line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Recipient_City", models.CharField(max_length=255)),
                ("Recipient_State", models.CharField(max_length=255)),
                ("Recipient_Zip_Code", models.CharField(max_length=255)),
                ("Recipient_Country", models.CharField(max_length=255)),
                (
                    "Recipient_Province",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Recipient_Postal_Code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Covered_Recipient_Primary_Type_1", models.CharField(max_length=255)),
                (
                    "Covered_Recipient_Primary_Type_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Covered_Recipient_Primary_Type_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Covered_Recipient_Primary_Type_4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Covered_Recipient_Primary_Type_5",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Covered_Recipient_Primary_Type_6",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Covered_Recipient_Specialty_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Covered_Recipient_Specialty_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Covered_Recipient_Specialty_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Covered_Recipient_Specialty_4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Covered_Recipient_Specialty_5",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Covered_Recipient_Specialty_6",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Covered_Recipient_License_State_code1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Covered_Recipient_License_State_code2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Covered_Recipient_License_State_code3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Covered_Recipient_License_State_code4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Covered_Recipient_License_State_code5",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Total_Amount_of_Payment_USDollars",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("Date_of_Payment", models.DateField()),
                ("Number_of_Payments_Included_in_Total_Amount", models.IntegerField()),
                (
                    "Form_of_Payment_or_Transfer_of_Value",
                    models.CharField(max_length=255),
                ),
                (
                    "Nature_of_Payment_or_Transfer_of_Value",
                    models.CharField(max_length=255),
                ),
                (
                    "City_of_Travel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "State_of_Travel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Country_of_Travel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Physician_Ownership_Indicator",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Third_Party_Payment_Recipient_Indicator",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Charity_Indicator",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Third_Party_Equals_Covered_Recipient_Indicator",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Contextual_Information",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Delay_in_Publication_Indicator",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Record_ID", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "Dispute_Status_for_Publication",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Related_Product_Indicator",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Covered_or_Noncovered_Indicator_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Product_Category_or_Therapeutic_Area_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Associated_Drug_or_Biological_NDC_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Associated_Device_or_Medical_Supply_PDI_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Covered_or_Noncovered_Indicator_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Product_Category_or_Therapeutic_Area_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Associated_Drug_or_Biological_NDC_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Associated_Device_or_Medical_Supply_PDI_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Covered_or_Noncovered_Indicator_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Product_Category_or_Therapeutic_Area_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Associated_Drug_or_Biological_NDC_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Associated_Device_or_Medical_Supply_PDI_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Covered_or_Noncovered_Indicator_4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Product_Category_or_Therapeutic_Area_4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Associated_Drug_or_Biological_NDC_4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Associated_Device_or_Medical_Supply_PDI_4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Covered_or_Noncovered_Indicator_5",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Indicate_Drug_or_Biological_or_Device_or_Medical_Supply_5",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Product_Category_or_Therapeutic_Area_5",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Associated_Drug_or_Biological_NDC_5",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Associated_Device_or_Medical_Supply_PDI_5",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Program_Year",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Payment_Publication_Date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
